name: Terraform
on:
  pull_request:
    branches: 
      - master
    types:
      - closed
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: terraform
        run: | 
         cd ~/localrepo
         export no_proxy=192.168.11.0/24
         git pull origin master
         cp variable.tfvars ../execute_terraform
         cd ../execute_terraform
         terraform init
         terraform plan -var-file credential.tfvars -var-file variable.tfvars
         echo "terraform apply -var-file credential.tfvars -var-file variable.tfvars -auto-approve"
         echo "Done!"
